/*
 * Copyright (C) 2018 Alessandro Falappa.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.dev.eth0.netbeans.plugins.regex.prefs;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.prefs.Preferences;
import org.openide.util.NbPreferences;

/**
 * Plugin options panel.
 * <p>
 * It is shown under the Miscellaneous category in Tools/Options dialog.
 *
 * @author Alessandro Falappa
 */
public class RegexOptionsPanel extends javax.swing.JPanel implements ActionListener {

    private final RegexOptionsPanelController controller;

    /**
     * Creates new form RegexOptionsPanel
     */
    public RegexOptionsPanel(RegexOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lHeading = new javax.swing.JLabel();
        lCol0 = new javax.swing.JLabel();
        ccbCol0 = new org.openide.awt.ColorComboBox();
        lCol1 = new javax.swing.JLabel();
        ccbCol1 = new org.openide.awt.ColorComboBox();
        lCol2 = new javax.swing.JLabel();
        ccbCol2 = new org.openide.awt.ColorComboBox();
        lCol3 = new javax.swing.JLabel();
        ccbCol3 = new org.openide.awt.ColorComboBox();
        lCol4 = new javax.swing.JLabel();
        ccbCol4 = new org.openide.awt.ColorComboBox();
        lCol5 = new javax.swing.JLabel();
        ccbCol5 = new org.openide.awt.ColorComboBox();
        lCol6 = new javax.swing.JLabel();
        ccbCol6 = new org.openide.awt.ColorComboBox();

        org.openide.awt.Mnemonics.setLocalizedText(lHeading, org.openide.util.NbBundle.getMessage(RegexOptionsPanel.class, "RegexOptionsPanel.lHeading.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lCol0, org.openide.util.NbBundle.getMessage(RegexOptionsPanel.class, "RegexOptionsPanel.lCol0.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lCol1, org.openide.util.NbBundle.getMessage(RegexOptionsPanel.class, "RegexOptionsPanel.lCol1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lCol2, org.openide.util.NbBundle.getMessage(RegexOptionsPanel.class, "RegexOptionsPanel.lCol2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lCol3, org.openide.util.NbBundle.getMessage(RegexOptionsPanel.class, "RegexOptionsPanel.lCol3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lCol4, org.openide.util.NbBundle.getMessage(RegexOptionsPanel.class, "RegexOptionsPanel.lCol4.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lCol5, org.openide.util.NbBundle.getMessage(RegexOptionsPanel.class, "RegexOptionsPanel.lCol5.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lCol6, org.openide.util.NbBundle.getMessage(RegexOptionsPanel.class, "RegexOptionsPanel.lCol6.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lCol2)
                            .addComponent(lCol3)
                            .addComponent(lCol1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ccbCol1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ccbCol2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ccbCol3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lCol4)
                            .addComponent(lCol5)
                            .addComponent(lCol6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ccbCol4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ccbCol5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ccbCol6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lCol0)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ccbCol0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lHeading))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lHeading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCol0)
                    .addComponent(ccbCol0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCol1)
                    .addComponent(ccbCol1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lCol4)
                    .addComponent(ccbCol4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCol2)
                    .addComponent(ccbCol2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lCol5)
                    .addComponent(ccbCol5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCol3)
                    .addComponent(ccbCol3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lCol6)
                    .addComponent(ccbCol6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openide.awt.ColorComboBox ccbCol0;
    private org.openide.awt.ColorComboBox ccbCol1;
    private org.openide.awt.ColorComboBox ccbCol2;
    private org.openide.awt.ColorComboBox ccbCol3;
    private org.openide.awt.ColorComboBox ccbCol4;
    private org.openide.awt.ColorComboBox ccbCol5;
    private org.openide.awt.ColorComboBox ccbCol6;
    private javax.swing.JLabel lCol0;
    private javax.swing.JLabel lCol1;
    private javax.swing.JLabel lCol2;
    private javax.swing.JLabel lCol3;
    private javax.swing.JLabel lCol4;
    private javax.swing.JLabel lCol5;
    private javax.swing.JLabel lCol6;
    private javax.swing.JLabel lHeading;
    // End of variables declaration//GEN-END:variables

    void load() {
        // read settings and initialize GUI
        final Preferences prefs = NbPreferences.forModule(PrefConstants.class);
        ccbCol0.setSelectedColor(new Color(prefs.getInt(PrefConstants.PREFKEY_COLOR_0, PrefConstants.DEFAULT_COLOR_0)));
        ccbCol1.setSelectedColor(new Color(prefs.getInt(PrefConstants.PREFKEY_COLOR_1, PrefConstants.DEFAULT_COLOR_1)));
        ccbCol2.setSelectedColor(new Color(prefs.getInt(PrefConstants.PREFKEY_COLOR_2, PrefConstants.DEFAULT_COLOR_2)));
        ccbCol3.setSelectedColor(new Color(prefs.getInt(PrefConstants.PREFKEY_COLOR_3, PrefConstants.DEFAULT_COLOR_3)));
        ccbCol4.setSelectedColor(new Color(prefs.getInt(PrefConstants.PREFKEY_COLOR_4, PrefConstants.DEFAULT_COLOR_4)));
        ccbCol5.setSelectedColor(new Color(prefs.getInt(PrefConstants.PREFKEY_COLOR_5, PrefConstants.DEFAULT_COLOR_5)));
        ccbCol6.setSelectedColor(new Color(prefs.getInt(PrefConstants.PREFKEY_COLOR_6, PrefConstants.DEFAULT_COLOR_6)));
        // listen to changes in form fields and call controller.changed()
        // Register listener on the textFields to detect changes
        ccbCol0.addActionListener(this);
        ccbCol1.addActionListener(this);
        ccbCol2.addActionListener(this);
        ccbCol3.addActionListener(this);
        ccbCol4.addActionListener(this);
        ccbCol5.addActionListener(this);
        ccbCol6.addActionListener(this);
    }

    void store() {
        // store modified settings
        final Preferences prefs = NbPreferences.forModule(PrefConstants.class);
        prefs.putInt(PrefConstants.PREFKEY_COLOR_0, ccbCol0.getSelectedColor().getRGB());
        prefs.putInt(PrefConstants.PREFKEY_COLOR_1, ccbCol1.getSelectedColor().getRGB());
        prefs.putInt(PrefConstants.PREFKEY_COLOR_2, ccbCol2.getSelectedColor().getRGB());
        prefs.putInt(PrefConstants.PREFKEY_COLOR_3, ccbCol3.getSelectedColor().getRGB());
        prefs.putInt(PrefConstants.PREFKEY_COLOR_4, ccbCol4.getSelectedColor().getRGB());
        prefs.putInt(PrefConstants.PREFKEY_COLOR_5, ccbCol5.getSelectedColor().getRGB());
        prefs.putInt(PrefConstants.PREFKEY_COLOR_6, ccbCol6.getSelectedColor().getRGB());
    }

    boolean valid() {
        return true;
    }

    // Actionistener interface
    @Override
    public void actionPerformed(ActionEvent e) {
        controller.changed();
    }
}
