package de.dev.eth0.netbeans.plugins.regex.ui;

import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.TopComponent;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//de.dev.eth0.netbeans.plugins.regex.ui//VeryNewUi//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "VeryNewUiTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "output", openAtStartup = false)
@ActionID(category = "Window", id = "de.dev.eth0.netbeans.plugins.regex.ui.VeryNewUiTopComponent")
@ActionReference(path = "Menu/Window", position = 1277)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_VeryNewUiAction",
        preferredID = "VeryNewUiTopComponent"
)
@Messages({
    "CTL_VeryNewUiAction=VeryNewUi",
    "CTL_VeryNewUiTopComponent=VeryNewUi"
})
public final class VeryNewUiTopComponent extends TopComponent {

    public VeryNewUiTopComponent() {
        initComponents();
        setName(Bundle.CTL_VeryNewUiTopComponent());
// --------------------------------------------------
//        code to initially expand the left section
// --------------------------------------------------
//        try {
//            jSplitPane1.setDividerLocation(999999);
//            Field m = BasicSplitPaneUI.class.getDeclaredField("keepHidden");
//            m.setAccessible(true);
//            m.set(jSplitPane1.getUI(), true);
//        } catch (IllegalArgumentException ex) {
//            Exceptions.printStackTrace(ex);
//        } catch (IllegalAccessException ex) {
//            Exceptions.printStackTrace(ex);
//        } catch (NoSuchFieldException ex) {
//            Exceptions.printStackTrace(ex);
//        } catch (SecurityException ex) {
//            Exceptions.printStackTrace(ex);
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        splitter = new javax.swing.JSplitPane();
        pMatch = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taText = new javax.swing.JTextArea();
        lGroups = new javax.swing.JLabel();
        lRegex = new javax.swing.JLabel();
        cbRegex = new javax.swing.JComboBox<>();
        bSave = new javax.swing.JButton();
        lStatus = new javax.swing.JLabel();
        lText = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tpGroups = new javax.swing.JTextPane();
        pReplace = new javax.swing.JPanel();
        lReplace = new javax.swing.JLabel();
        txReplace = new javax.swing.JTextField();
        lReplaced = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taReplaced = new javax.swing.JTextArea();

        jTextArea3.setColumns(20);
        jTextArea3.setRows(3);
        jScrollPane4.setViewportView(jTextArea3);

        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane5.setPreferredSize(new java.awt.Dimension(100, 60));

        jTextPane2.setPreferredSize(new java.awt.Dimension(100, 50));
        jScrollPane5.setViewportView(jTextPane2);

        setMinimumSize(new java.awt.Dimension(600, 185));
        setLayout(new java.awt.BorderLayout());

        splitter.setResizeWeight(0.7);
        splitter.setContinuousLayout(true);
        splitter.setOneTouchExpandable(true);

        taText.setColumns(20);
        taText.setRows(3);
        jScrollPane2.setViewportView(taText);

        org.openide.awt.Mnemonics.setLocalizedText(lGroups, org.openide.util.NbBundle.getMessage(VeryNewUiTopComponent.class, "VeryNewUiTopComponent.lGroups.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lRegex, org.openide.util.NbBundle.getMessage(VeryNewUiTopComponent.class, "VeryNewUiTopComponent.lRegex.text")); // NOI18N

        cbRegex.setEditable(true);
        cbRegex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2" }));

        org.openide.awt.Mnemonics.setLocalizedText(bSave, org.openide.util.NbBundle.getMessage(VeryNewUiTopComponent.class, "VeryNewUiTopComponent.bSave.text")); // NOI18N

        lStatus.setFont(lStatus.getFont().deriveFont(lStatus.getFont().getSize()-2f));
        org.openide.awt.Mnemonics.setLocalizedText(lStatus, org.openide.util.NbBundle.getMessage(VeryNewUiTopComponent.class, "VeryNewUiTopComponent.lStatus.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lText, org.openide.util.NbBundle.getMessage(VeryNewUiTopComponent.class, "VeryNewUiTopComponent.lText.text")); // NOI18N

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(100, 60));

        tpGroups.setPreferredSize(new java.awt.Dimension(100, 50));
        jScrollPane1.setViewportView(tpGroups);

        javax.swing.GroupLayout pMatchLayout = new javax.swing.GroupLayout(pMatch);
        pMatch.setLayout(pMatchLayout);
        pMatchLayout.setHorizontalGroup(
            pMatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMatchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pMatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lRegex)
                    .addComponent(lText)
                    .addComponent(lGroups))
                .addGap(11, 11, 11)
                .addGroup(pMatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pMatchLayout.createSequentialGroup()
                        .addComponent(cbRegex, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bSave))
                    .addComponent(lStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pMatchLayout.setVerticalGroup(
            pMatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMatchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pMatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lRegex)
                    .addComponent(cbRegex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pMatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lText)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pMatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lGroups)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        splitter.setLeftComponent(pMatch);

        org.openide.awt.Mnemonics.setLocalizedText(lReplace, org.openide.util.NbBundle.getMessage(VeryNewUiTopComponent.class, "VeryNewUiTopComponent.lReplace.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lReplaced, org.openide.util.NbBundle.getMessage(VeryNewUiTopComponent.class, "VeryNewUiTopComponent.lReplaced.text")); // NOI18N

        taReplaced.setEditable(false);
        taReplaced.setColumns(20);
        taReplaced.setRows(3);
        jScrollPane3.setViewportView(taReplaced);

        javax.swing.GroupLayout pReplaceLayout = new javax.swing.GroupLayout(pReplace);
        pReplace.setLayout(pReplaceLayout);
        pReplaceLayout.setHorizontalGroup(
            pReplaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pReplaceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pReplaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lReplaced)
                    .addComponent(lReplace))
                .addGap(5, 5, 5)
                .addGroup(pReplaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txReplace, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                .addContainerGap())
        );
        pReplaceLayout.setVerticalGroup(
            pReplaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pReplaceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pReplaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lReplace)
                    .addComponent(txReplace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pReplaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lReplaced)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );

        splitter.setRightComponent(pReplace);

        add(splitter, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSave;
    private javax.swing.JComboBox<String> cbRegex;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JLabel lGroups;
    private javax.swing.JLabel lRegex;
    private javax.swing.JLabel lReplace;
    private javax.swing.JLabel lReplaced;
    private javax.swing.JLabel lStatus;
    private javax.swing.JLabel lText;
    private javax.swing.JPanel pMatch;
    private javax.swing.JPanel pReplace;
    private javax.swing.JSplitPane splitter;
    private javax.swing.JTextArea taReplaced;
    private javax.swing.JTextArea taText;
    private javax.swing.JTextPane tpGroups;
    private javax.swing.JTextField txReplace;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
    }

    @Override
    public void componentClosed() {
    }

    void writeProperties(java.util.Properties p) {
        System.out.println("de.dev.eth0.netbeans.plugins.regex.ui.VeryNewUiTopComponent.writeProperties()");
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        System.out.println("de.dev.eth0.netbeans.plugins.regex.ui.VeryNewUiTopComponent.readProperties()");
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
